server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /position/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: capture-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: backend
      __path__: /logs/backend/*log